name: StunDB
ip: 127.0.0.1
port: ${application.port}
capacity:
  publicCache: 9999
  internalCache: 256
timeouts:
  tcpReadTimeout: 10
  tcpWriteTimeout: 10
tcpClient:
  threads: 10
digestAlgorithm: SHA-256
seeds:
  - 127.0.0.1:8001
  - 127.0.0.1:8000